### ISSUE TITLE
Fix relative paths

### ISSUE THREAD

**Issue by cmungall** [hrshdhgd/CoderGPT#7]
When I try and run from a pipx install:

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/cjm/.local/pipx/venvs/codergpt/lib/python3.11/src/codergpt/extensions.yaml'
```

this is the cause
https://github.com/hrshdhgd/CoderGPT/blob/e451637bd389a00582a6ac19c1b9c64a4cca8f9c/src/codergpt/constants.py#L8

No need for `src`

I also recommend putting this into an explicit config folder unser src/codergpt, make an __init__, see:

https://github.com/INCATools/ontology-access-kit/blob/main/src/oaklib/datamodels/__init__.py

**Comment by hrshdhgd** [comment]
Thanks Chris! Fixed by https://github.com/hrshdhgd/CoderGPT/commit/f364f7edfa610365e2e5bd5e185baa3c5675bb25
